# Generated by Django 3.2 on 2023-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Оценка'),
        ),
    ]
